name: Test

on:
  push:
    branches: [ main, staging, trying ]
    paths-ignore:
        - .git*
        - scripts/**
        - README.md

jobs:
  all-tests:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        rust: [stable]

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout...
        uses: actions/checkout@v2

      - name: rustup
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy

      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all
